### ISSUE TITLE
Missing last-modified-date for container-metadata

### ISSUE THREAD

**Issue by Mossaka** [WebAssembly/wasi-blobstore#4]
Currently the container-metadata is defined as the following

```wit
 // information about a container  
record container-metadata {
    // the container's name
    name: container-name,
    // date and time container was created
    created-at: timestamp,
}
```

I am curious to know if `last-modified-date` should be a variable name replacing `created-at`, or keep both if we found both use cases useful. @stevelr

**Comment by autodidaddict** [comment]
My exposure to container metadata in different systems is that not all of them keep track of this data. Further, the ones that do end up confusing people because we need to know ahead of time whether adding/removing blobs to the inside of a container constitutes a container modification or whether container modifications are limited only to things like changing the name.

A field like `last-modified-date` could confuse people, especially if only some providers can expose this data, so developers would have to know not to rely on it anyway.

**Comment by thomastaylor312** [comment]
Going to close this for now as won't fix
